sfsdf

diff --git a/.github/workflows/test_and_build.yml b/.github/workflows/test_and_build.yml
--- a/.github/workflows/test_and_build.yml
+++ b/.github/workflows/test_and_build.yml
@@ -32,6 +32,8 @@ jobs:
         run: make build
 
       - name: test exit
-        if: 70 < 50
-        run: exit 1
+        if: 40 < 50
+        run: |-
+          echo "::error ::Total unit test coverage is below threshold"
+          exit 1
 
